---
argument_specs:
  main:
    short_description: Install Python pip packages
    description:
      - Installs Python packages using pip
      - Expects pre-aggregated data from playbook
    options:
      pip_packages:
        description: List of pip packages to install
        type: list
        elements: dict
        default: []
        options:
          name:
            description: Package name or git URL
            type: str
            required: true
          state:
            description: Package state
            type: str
            choices:
              - present
              - absent
              - latest
            default: latest

      pip_executable:
        description: Path to pip executable
        type: path
        required: false

      pip_system_pip_path:
        description: Path to system pip
        type: path
        default: /usr/local/bin/pip3

      pip_miniconda_path:
        description: Path to miniconda installation
        type: path
        default: /opt/homebrew/Caskroom/miniconda/base
